### ISSUE TITLE
Git fork selecting custom git instance doesn't change

### ISSUE THREAD

**Issue by efsjouw** [andy-5/wslgit#121]
I used the install.bat with a successful installation and placed the wslgit.exe somewhere on my machine and added it to PATH.

However when I try to set a custom git instance in Fork it doesn't appear to change?

![image](https://user-images.githubusercontent.com/7520611/158768699-dfc4c8e5-8ab6-4cd1-8f1a-718643189251.png)

**Comment by carlolars** [comment]
Symlinks are 0 kB size, that is correct.

But since you have the `resources` folder I guess that you cloned this repository? Easiest is to just download the latest release zip from https://github.com/andy-5/wslgit/releases/latest and extract, and from there run the install.bat script :)

**Comment by Patrick-clone** [comment]
I have the same problem. I cannot select the `bin/git.exe` instance in Git Fork. Does anyone have a solution?

**Comment by colinshipton** [comment]
I also have the same problem, it used work fine and I had to to make a few updates (git inside WSL and wslgit due to https://github.com/andy-5/wslgit/issues/134) and now it no longer works.

I tried manually editing the GitInstancePath in Fork settings.json file and when starting Fork I get the following error:
```
System.InvalidOperationException: Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at Fork.Git.Interaction.GitRequest.Execute(Boolean silent)
```

**Comment by Asthenean** [comment]
With the newest version it appears to work fine with git in wsl now, at least for me (had to make two ssh keys as well, one for wsl and one for windows) fork appears to just use git for windows but it's fine for now. No issues yet (maybe some other isuse was resolved?)

**Comment by buencaminoje** [comment]
Upon looking at the logs, I think the -version does not work on the current git.exe in bin

`⚠️ 2023-02-15 12:18:03.704 Shell request 'C:\wslgit\bin\git.exe' with arguments 'version' failed: ''`

**Comment by Stanzilla** [comment]
Doesnt work for me anymore either. Haven't used wslgit in a while and just wanted to try it again today

**Comment by Mika-** [comment]
I had this same thing happen and the problem was missing wslgit.exe under the cmd directory. No idea how zip extraction failed, as it works fine when retrying

**Comment by mundodisco8** [comment]
Had this same issue. I copied the latest release (which was the same that I had downloaded as WSLGit has not updated since I installed it) on top of the old one, and rerun `install.bat`. Instead of running on a command line with privileges, I ran it with the new `sudo` available in windows. Output was this

```
'git.exe' already exist.


'bin\git.exe' already exist.

'bin\Fork.RI' already exist.

'bin\sh.exe' already exist.

'bin\bash.exe' already exist.

Installation successful!

(Optional) Add to the Windows Path environment variable:
 C:\Program Files\WSLGit\cmd

Press any key to continue . . .
```

The only difference is that now I have four symlinks in the folder and before running it I had only three (I can't remember which one was created)

<img width="598" height="264" alt="Image" src="https://github.com/user-attachments/assets/36c19be6-ac6f-42a5-8772-386398c29518" />

I can change now Git the instance in Fork

<img width="577" height="314" alt="Image" src="https://github.com/user-attachments/assets/5cdc42a2-04cd-4051-845c-05c2ad28fb6e" />

**Comment by mundodisco8** [comment]
~Nope, it doesn't work. I updted Git (might not be related, but it's when I noticed Fork being ultraslow), checked again and Fork reverted to "Fork Git Instance". Now, no matter what I do, I can't get it to select WSLGit as its Git....~

I removed all the links in my installation folder (the bin folder, plus a symlink named git.exe in cmd), so basically, delete WSLGit and re-download, in an installation path WITHOUT SPACES on it (so you can't do `Program Files`, but you can do `C:\Users\YOURUSER\AppData\Local\WSLGit\` as long as your username doesn't have spaces on it).
Command line with privileges -> run install.bat (alternatively, command line without privileges, `sudo install.bat`)

The symlinks are now recreated. 

I had to close Fork and open it again, and Fork now uses WSLGit

<img width="604" height="149" alt="Image" src="https://github.com/user-attachments/assets/6cb8d2bb-e616-4813-8574-570fa8f07e24" />

The no spaces bit is needed because otherwise, when you do a rebase, it will complain that `Fork.ri` is not executable. The Readme says that you can change the permissions, but if it's stored in your NTFS partition, chmod doesn't work on it. It needs to be stored somewhere without spaces on its path.

So far, so good!
